version: '3'

services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: zepartner
    ports:
      - "5432:5432"
    volumes:
      - ze_data:/bitnami/postgresql
volumes:
  ze_data: