services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: zepartner
    ports:
      - "5432:5432"
    volumes:
      - ze_data:/var/lib/postgresql/data
      - ./db/init-postgis.sh:/docker-entrypoint-initdb.d/init-postgis.sh
    entrypoint: ["/docker-entrypoint-initdb.d/init-postgis.sh"]

  db-shadow:
    image: postgres:16
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: zepartner
    ports:
      - "5433:5432"
    volumes:
      - ze_data_shadow:/var/lib/postgresql/data
      - ./db/init-postgis.sh:/docker-entrypoint-initdb.d/init-postgis.sh
    entrypoint: ["/docker-entrypoint-initdb.d/init-postgis.sh"]


volumes:
  ze_data:
  ze_data_shadow: